### PR TITLE
is09: add testing for Nodes which support System API discovery

### PR DESCRIPTION
**Pull request by andrewbonney**
Work in progress

Intended to test that a Node can discover a System API. Could be expanded to ensure it correctly implements the configuration contained within.

This is currently untested against any Nodes which implement System API discovery.

Once the testing pattern is resolved it should be possible to apply it to IS-10 cases too.

### CODE REVIEW

**Comment by andrewbonney** [comment]
As noted this is currently untested on a Node implementing IS-09, but as soon as I can get hold of one (or anyone else can) we can test it properly.

**Comment by garethsb-sony** [comment]
The biggest problem I have is that it's not clear to me what a Node should actually do before it discovers a System API, and while it's waiting for a response, and whether it should retry if it doesn't get a response after a time out or connection error, and whether it should attempt discovery etc. repeatedly perhaps with back off, and whether it should 'refresh' its discovered information ever if it doesn't get power cycled...

**Comment by bgilmer77** [comment]
@garethsb-sony you bring up a number of Most Excellent points.  Given that the System Resource is likely to get hammered after a power outage or some other major interruption, the answers to your questions are critical.  Seems this is a topic for discussion with John Mailhot - no?

**Comment by garethsb-sony** [comment]
Yes, you're correct, this is a topic for the _NMOS IS-09 System API_ activity group, and JT-NM TR-1001-1. That document says that "Media Nodes [...] shall check at re-start, before generating any multicast outputs" but on the other hand that "if the System Resource is not available, Media Nodes shall behave [as if they had found it]". There's certainly a tension between wanting to start up streams quickly after a power/network interruption and not wanting to start up streams when connected to an unfamiliar 'System'.

**Comment by andrewbonney** [comment]
@garethsb-sony I don't expect these tests to offer complete coverage of the spec at the moment, but I'm hoping that the tests which are currently included aren't particularly contentious. There are certainly issues which need dealing with at the spec level before other items can be turned into tests.

The question is, is it worth me resolving the merge conflicts that have appeared since this PR first came up, or if there are concerns over testing this area at all should I just abandon the PR?

**Comment by andrewbonney** [comment]
> Presumably 'v1.0' would make a better example than 'v1.2', if I've understood correctly?

Yes, I'll update.

**Pull request merged**
