### PR TITLE
Fix wrong FAIL message param

### PR DESCRIPTION
**Pull request by garethsb-sony**

### CODE REVIEW

**Comment by garethsb-sony** [comment]
@andrewbonney @dannymeloy

The Travis CI checks failed on an unrelated piece of code, although weirdly similar to the mistake this PR is fixing!

I don't quite understand why this is the first time ESLint is reporting the problem at https://github.com/AMWA-TV/nmos-testing/blame/master/nmostesting/suites/IS1001Test.py#L477, it's obviously been wrong for 10 months.

Maybe ESLint only just added this check?

**Comment by andrewbonney** [comment]
I think I've seen reports from others internally of some linting having become more strict in the past few days.

**Comment by garethsb-sony** [comment]
I know there's an issue to work on the IS-10 tests, but that lint issue is going to come up for every PR until it's fixed. Would you have time to fix it?

**Comment by andrewbonney** [comment]
Yes, I should be able to get the linting issue sorted

**Pull request merged**
