### PR TITLE
json: handle potential for different exception names. Resolves #261

### LINKED ISSUE #261: SimpleJSON causes uncaught exceptions
We've hit this before in https://github.com/AMWA-TV/nmos-testing/issues/2

If a system has simplejson installed it will be used in preference to the built in JSON parser. Unfortunately it has different exception names which cause things to fail. I don't have a good solution to this yet (and would have thought it'd be a more common problem with a best practice solution), but we should probably keep an issue open as a reminder for whenever it comes up.

### PR DESCRIPTION
**Pull request by andrewbonney**
I'd prefer to catch a more specific exception, but this seems to be the only straightforward way around the issue of simplejson vs. json at present.

### CODE REVIEW

**Comment by garethsb-sony** [comment]
I don't quite understand this. The simplejson module does seem to have a `JSONDecodeError`. The json module didn't pre python 3.5. Is it that we're referring to `json.decoder.JSONDecodeError` rather than `json.JSONDecodeError`?

**Comment by andrewbonney** [comment]
The json module throws a `json.decoder.JSONDecodeError` but simplejson (if installed) throws a `simplejson.errors.JSONDecodeError`. I haven't come across a way to refer to these in a common fashion beyond resorting to the `ValueError` which they're both based upon.

**Comment by garethsb-sony** [comment]
Yes, but aren't both of those aliased to `json.JSONDecodeError`?

**Comment by andrewbonney** [comment]
Quite possibly. I hadn't come across that but can try it out.

**Comment by garethsb-sony** [comment]
> Quite possibly. I hadn't come across that but can try it out.

I'm only going on the docs for both modules. Fingers crossed!

**Comment by andrewbonney** [comment]
Could you point me at the bit of the simplejson docs which indicate that? I've just tried and encountered the same issue.

**Comment by garethsb-sony** [comment]
https://simplejson.readthedocs.io/en/latest/#simplejson.JSONDecodeError

And https://github.com/simplejson/simplejson/commit/104b40fcf6aa39d9ba7b240c3c528d1f85e86ef2 which seems to imply you were never supposed to import JSONDecodeError from the json.decoder module.

**Pull request merged**
