### PR TITLE
Include spec repos in docker image

### LINKED ISSUE #661: Build Docker container image with an initial copy of the specs for all the auto tests
To support deployment in environments without an internet connection, it would be helpful if the Docker image could run without using git to clone the spec repos. Could a copy of the current state of these repos be included in the image at the point that it's built?

The testing tool should continue to warn that the specs are stale (and ideally how many days/months/years stale!) - perhaps even in the UI as well as the log.

The spec repos are not huge in any case, but perhaps we could avoid bloating the container unnecessarily by trimming down the repo contents included in the image to only the `APIs` directories for each branch?

### PR DESCRIPTION
**Pull request by garethsb**
Experiment to resolve #661.

### CODE REVIEW

**Comment by garethsb** [comment]
With first commit, it's basically working, but only fetched default branch so testing tool logs no branch available if you try to test a different version. I hoped second commit would fix it, but no. Need some expert help. :-)

**Comment by rbgodwin-nt** [comment]
Hi @garethsb. Can you provide steps to reproduce the problem:

- Where changes are made in the config to choose a different branch
- The location of the error you see.
- Specific test scenarios we would like to run (specific versions we must be able to run)

I'll first reproduce the problem and then look into if I can determine a fix.

**Comment by garethsb** [comment]
Run the testing tool, run the IS-05 Connection API test suite v1.1, everything works. Select v1.0 and try to run, see message about missing branch.

**Comment by garethsb** [comment]
Randy and I realised each `run: git fetch` needed a `working-directory`, that's fixed it.

**Comment by garethsb** [comment]
Now [`dev-dddd07d`](https://hub.docker.com/layers/amwa/nmos-testing/dev-dddd07d/images/sha256-e728694e30b6a5856375d56e9cae72416f429b18d0d4e6ad2d1ed613ce93e898?context=explore) is 267.91MB vs. [`master-f7b2c27`](https://hub.docker.com/layers/amwa/nmos-testing/master-f7b2c27/images/sha256-09d39fe21769a0f36c54bb5b1c0713ccb01e9a1d2be036fd8badc11637a41874?context=explore) which is 258MB. Worth it?

**Pull request merged**
