### PR TITLE
Added support for v1.0 and v1.1 in TestIS0402

### PR DESCRIPTION
**Pull request by jasperpeeters**
Added downgrade_resource functionality
Implemented in basic resource registering tests

### CODE REVIEW

**Comment by andrewbonney** [comment]
Might be worth adding a check in each test for whether the API version under test is > v1.2 (there's a major/minor version attribute in the apis object which should help). At present it looks like the logic will see that v1.3 is != v1.2, and then attempt to downgrade it. Otherwise LGTM

**Comment by jasperpeeters** [comment]
I see.. 

By the way: does it make sense already to update the sample data to v1.3?

**Comment by andrewbonney** [comment]
We can do, but it would be good to make sure the tests are 'future proofed' anyway so that they don't give false positives for versions which aren't yet fully supported by the test suite.

**Comment by jasperpeeters** [comment]
@andrewbonney 
I improved the version check and made it a bit more future-proof (added major version check).
The tests are currently still based on v1.2 test_data -- once this data is updated, the test can be easily updated (check if < 3 for downgrade).

**Comment by andrewbonney** [comment]
Thanks Jasper

**Pull request merged**
