### PR TITLE
Export current configuration when saving a JSON file

### PR DESCRIPTION
**Pull request by andrewbonney**
A starting point for #323. Doesn't print to the results page yet, but it's included in the JSON.

I note also that the JSON doesn't indicate which API version(s) were tested which is another omission.

### CODE REVIEW

**Comment by andrewbonney** [comment]
I'd quite like to include some form of version identification in the file too, but it's hard to manage that manually, and there's no guarantee a git hash will be available. One possibility might be to take the md5sum or similar of the file relating to the test suite used. This wouldn't catch all changes, but ought to get the most important ones.

**Comment by garethsb-sony** [comment]
Disadvantage of an md5sum of the source file is that we'd have to separately track md5sums per commit or something to check which version it corresponded to?

**Comment by garethsb-sony** [comment]
> I note also that the JSON doesn't indicate which API version(s) were tested which is another omission.

I see `"endpoints"` now in the JSON, perfect. In the HTML results page, it'd be nice to add API version also. At the moment, the title is like:

"Result for test suite **IS-05 Interaction with Node API** on **http://10.10.0.1:1234**"

The URL host and port just happen to be the `base_url` that drops out from the endpoint loop, so in this case the Connection API.

Would it be better to tighten up the title / put both endpoints up here at the top, or leave that alone, and just add `"endpoints"` to the config at the bottom of the page?

**Comment by andrewbonney** [comment]
I think we ought to fix the title really. Particularly when you're testing two services which run on different ports it can be confusing. `base_url` is a bit of a throwback to when it could only test one API at a time.

**Comment by andrewbonney** [comment]
That commit does change the JSON slightly, but I think it's worth doing,

**Comment by garethsb-sony** [comment]
Agreed!

**Pull request merged**
