### PR TITLE
Enable non-interactive testing

### LINKED ISSUE #43: Feature Request: Command line operation
It would be useful to be able to trigger a test set by providing the required fields (IPs/Ports/Versions etc) from the command line as an alternative to the web interface. This would make it much more straightforward to use the test suite for automated integration testing. Output of test results would be to stdout/file, likely in a machine readable format (XML/JSON).

### PR DESCRIPTION
**Pull request by andrewbonney**
Will resolve #43 

This is just a bit of refactoring with the aim to permit command line operation triggered by automated testing jobs.

I'd appreciate thoughts on whether the unit under test should be passed in via command line argument or use of the existing Config file. Equally, if passing things in via the command line should it be possible to override Config.py values via this method?

Also, what format would the test results be most useful in? I'm intending that the exit code reflects the worst test result encountered in the pass, but the detail of failures could be formatted however is most useful.

### CODE REVIEW

**Comment by garethsb-sony** [comment]
Here's some brainstorming!

> Also, what format would the test results be most useful in?

I guess the test runner should support one or more of the de-facto standard formats for CI, like the "JUnit XML Report" ANT task format (though there doesn't seem to be a great spec for that), and ideally some less verbose/more readable options too, such as supported by the Python ``unittest`` module.

> I'm intending that the exit code reflects the worst test result encountered in the pass

I think that's reasonable. A common idiom is that it reflects the _number_ of failed tests, but some platforms don't like exit codes larger than 255, and in our case, the 'level' seems a useful output, with 0 being 'Pass'.

> I'd appreciate thoughts on whether the unit under test should be passed in via command line argument or use of the existing Config file.

I think the Config file makes sense for things which are largely static. Other things that are more dynamic make more sense as command line arguments to me.

E.g. It would be useful if we could run a single test case by name, and for e.g. CMake/CTest integration if we had a 'discovery' mode that listed the test case names, one per line.

(Since we have multiple test suites only some of which are applicable for different systems-under-test, the suite should need to be specified in all the above use-cases.)

E.g.

(I haven't included something like ``--noninteractive`` everywhere below, because specifying the test suite seemed enough of an indication.)

Discovery:

```
$ python3 nmos-test.py --suite IS-04-01 --list
auto
test_01
...
test_17
$
```
(or better, but this applies to interactive/webapp mode too, with "auto_01", "auto_02", ... instead of "auto")

Since test _cases_ are added/removed much more frequently than test _suites_ and you'd have to know the test suites that applied to your system-under-test, I don't propose adding a ``--list-suites`` function as well even though it'd be trivial.

Single test case:

```
$ python3 nmos-test.py --suite IS-04-01 test_13
$
```
(no output on success, exit code 0)

Entire test suite:

```
$ python3 nmos-test.py --suite IS-04-01
$
```
(no output on success, exit code 0)

CI report format:

```
$ python3 nmos-test.py --suite IS-04-01 --report=junit
<?xml version="1.0" encoding="UTF-8" ?> 
<testsuites id="20190401_123456" name="01/04/2019 12:34:56" tests="42" failures="0" time="42.345">
  <testsuite id="IS0401Test" name="IS-04-01" tests="42" failures="0" time="42.345">
      ...
  </testsuite>
</testsuites>
$
```
(no output on success, exit code 0)

One downside of the JUnit XML format above is that it requires the XML isn't output until the end because the number of tests and failures are included as attributes. There are better streaming XML formats, but I don't know about CI support for those.

I'll stop and hit 'Comment' now before this gets even longer!

**Comment by andrewbonney** [comment]
Thanks Gareth, that's really useful.

**Comment by andrewbonney** [comment]
Lots of cleanup required yet, but this appears to work.

**Comment by andrewbonney** [comment]
I think this is worth a scan now. I'm sure there will be improvements to make in the future, but hopefully it's about there is a minimum viable product.

The interactive test suite should work exactly as it did before. The non-interactive mode is then triggered by setting the --suite argument, with various other arguments documented in --help. Using the --output argument and specifying a file will write a test result file in JUnit XML format (hopefully compatible with various parsers). Without the --output argument the results are printed to screen in a basic format for now (this could be improved upon in the future).

I've included suggestions of which test states may be considered as pass/fail/error/skipped in JUnit XML parlance, but these may need to be tweaked.

**Comment by garethsb-sony** [comment]
Great work, Andrew.

A couple of minor quibbles (mostly with the junit-xml module or perhaps JUnit XML format itself!)

* Disabled and ignored test cases get counted in the suite's 'disabled' count, but still show up in the XML as ``<testcase>`` elements, as if they were passing - ``is_enabled`` seems to make no difference - which I feel is misleading. (They're also still listed in the basic output format.) Not sure if the only solution is to use "skipped" instead.
* TestResult.WARNING is counted as error. I think error is intended for the test suite itself going wrong (like the uncaught exception message in the interactive runner), so I think warning ought to be reported as a ``<failure>``.
* Mis-matched ``--ip`` and `--port`` and ``--version`` cause an uncaught exception
* I can't work out why, but some ``<testcase>`` elements end up with no ``time`` attribute, possibly those with a time < 0.01s?

**Comment by garethsb-sony** [comment]
As part of #150, we'd probably add the ability for ``--selection`` to be an ``narg`` space-separated list, if that's OK, unless you get to that first?

**Comment by andrewbonney** [comment]
Thanks Gareth. I'll address those issues. I'm not going to add `--selection` for now, but can always come back to it if anything needs adding after your contributions.

**Comment by andrewbonney** [comment]
The time issue may be another Windows/Linux difference. I've checked here and it always shows up, even for very small times. I'll see if I can replicate it in a Python shell on a Windows host.

**Comment by andrewbonney** [comment]
This is probably why... https://github.com/kyrus/python-junit-xml/blob/master/junit_xml/__init__.py#L171. I suspect 0.0 (as reported on Windows for very small times) evaluates to something falsy, so as that line doesn't explicitly check for 'None' it gets omitted.

**Pull request merged**
