### PR TITLE
Refactor Query API subscription requests

### LINKED ISSUE #172: Refactor creation of Query API subscriptions
We're creating subscriptions in lots of places now and there's lot of repeated code (with errors creeping in). This needs refactoring into one or two methods to create the required JSON payload and carry out the subscription requests.

### PR DESCRIPTION
**Pull request by andrewbonney**
Resolves #172 

This will make more sense once the first HTTPS PR is merged, as it's based on top of it.

### CODE REVIEW

**Comment by andrewbonney** [comment]
This was my initial plan. The reason I didn't was down to the handling of 501/400 codes and a desire to give clear enough error responses, in particular with tests like test_24_1. I could modify it in this way, but it may have to give a more generic error message if it hits a 501/400.

**Comment by garethsb-sony** [comment]
My feeling is that these tests are focused on the WebSocket aspect, and therefore a more generic error message that says something like "Query API signalled that it does not support the subscription parameters: {}" for the 501/400 cases, that can be produced inside `post_subscription`, is good enough, given how it will simplify the tests. If the error is actually related to the lack of basic query/RQL/etc. the previous test case will also fail.

**Comment by andrewbonney** [comment]
Ok, I'll re-work that bit.

**Comment by andrewbonney** [comment]
Hopefully that's better. It also fixes a bug I'd introduced in re-working test_29, and a potential race condition in test_31.

**Pull request merged**
