### PR TITLE
is0401: add test for 200 on initial registration. Resolves #179

### LINKED ISSUE #179: IS-04-01: Add test for "Node Encounters HTTP 200 On First Registration"
See https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/docs/4.1.%20Behaviour%20-%20Registration.md#node-encounters-http-200-on-first-registration

### PR DESCRIPTION
**Pull request by andrewbonney**

### CODE REVIEW

**Comment by andrewbonney** [comment]
I was going to add a check along those lines, but I noted in testing that at present our implementation issues a DELETE first when it needs to re-register. As such the POST check becomes a little redundant as long as the mock resource provides the expected 200 code for those implementations that do POST first.

I'd be happy to correct this at our end and adjust the test, but I was a little uncertain as that behaviour seems to provide the same end result, so I'm not sure if it constitutes a problem that needs flagging. What are your thoughts?

**Comment by garethsb-sony** [comment]
Hmm, what does "when it needs to re-register" mean, i.e. how does it detect that and decide to lead with a DELETE?

**Comment by andrewbonney** [comment]
As things stand, when the Node first starts up it issues a DELETE before its first POST, so it assumes the potential for an error condition and performs the mitigation without first checking for a 200. The same procedure is used if it gets a 404 from a heartbeat.

**Comment by garethsb-sony** [comment]
Thanks for the explanation.

It seems pessimistic to issue the DELETE before first POST, but I can understand the logic. The [docs do say](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/docs/4.1.%20Behaviour%20-%20Registration.md#node-encounters-http-200-on-first-registration) "If a Node is restarted, its _first_ action upon discovering a Registration API is to register its 'Node' resource." (That is 'is' not 'SHALL' though!)

I don't understand the logic after a 404 from a heartbeat - what's the scenario where after a heartbeat 404, the Registry returns anything other than a 404 from the DELETE? Optimistic replication potentially, I suppose...

Anyway, I'm happy with the test as it stands - thanks - and I can't see that the behaviour of your implementation presents problems.

**Comment by andrewbonney** [comment]
> I don't understand the logic after a 404 from a heartbeat - what's the scenario where after a heartbeat 404, the Registry returns anything other than a 404 from the DELETE? Optimistic replication potentially, I suppose...

I think it's historic laziness to be honest. The same code path is hit upon initial registration and upon a 404 from heartbeat, so it happens in both cases. There are a few areas of the registration logic that I know could be improved (despite having no functional issue), so it's certainly one I'll be coming back to.

**Pull request merged**
