### PR TITLE
IS-11 basic tests

### PR DESCRIPTION
**Pull request by N-Nagorny**

### CODE REVIEW

**Comment by alabou** [comment]
The files nmostesting/suites/IS1101Test.py and nmostesting/suites/IS1102Test.py are likely to conflict with actual test suite files under development by Matrox.

**Comment by garethsb** [comment]
I suggest working publicly so that becomes clearer sooner and we avoid wasted effort...

**Comment by garethsb** [comment]
Nikita, I've taken 2cf3a525e65e160058c2b78bc4b8aaf7809220c8 and 020a4bbac9f1d4e099c59f532a71670d61cec303 into the `AMWA-TV:is-11` branch. Hoping we can move things along...

**Comment by garethsb** [comment]
@N-Nagorny I'm going to close this PR, so we can all focus on small PRs on the `is-11` branch. Hope that's OK!

**Pull request closed without merging**
