### PR TITLE
Added no-cache, no-store to repsonse header

### LINKED ISSUE #128: "Run" button does not reactivate after executing a single test
I ran an IS-04/-05 interaction test (test 08, to be precise). I then clicked my browser's back button because I wanted to run all the tests, but the button at the bottom of the interface never went back to "Run" but was stuck on "Executing test". Running all the tests doesn't cause this misbehavior.

### PR DESCRIPTION
**Pull request by jasperpeeters**
Should resolve #128 

Tested with Firefox 65.0 and Chrome Version 72.0.3626.96 (although I did not have this issue with Chrome in first place).

Interested in other browsers (/versions) :)

### CODE REVIEW

**Comment by billt-hlit** [comment]
This fixes the problem with Firefox 65 on Linux I was seeing, but it also means that the IP address and port number fields get wiped clean when I click the back button as well. Oh well.

It appears that "no-cache" is both necessary and sufficient to fix the problem, so "no-store" is unnecessary in my case.

Thanks, Jasper.
Bill

**Comment by jasperpeeters** [comment]
I added saveSettings + loadSettings functionality. Tested with Firefox 65.0.1 and Chrome 72. 

Using the test should now be a bit more comfortable.

**Comment by andrewbonney** [comment]
Thanks for this Jasper. I've given it a try and it mostly works, but I'm finding that the 'API Version' and 'Test Selection' dropdowns always revert to the top item in the list. 'Select test' and the input boxes work fine however.

Would it also make sense to change the behaviour of the 'Go Back' link on the test results page so that it has access to the benefits of the stored settings?

**Comment by garethsb-sony** [comment]
I've had a problem all along that the API version reverts to the default value (e.g v1.2 for IS-04 tests). Not sure if that's related.

Tangentially relevant: we are prepping a PR which makes the drop-down into a multi-select list box, and makes the first cell in each row of the results a button to re-run just that test. (Possibly also a little overlap with #147 refactoring therefore.)

**Comment by jasperpeeters** [comment]
Ok that is weird. I re-checked now a couple times and on my side the API Version as well as the Test selection is always the value I got before. Also the "Go back" button has the same behavior as the browsers back button here, however, I think that could be forced with [window.history.back();](https://www.w3schools.com/jsref/met_his_back.asp) if that is just a coincidence on my side.

What are you using (browser)? I will test this on a Windows PC tomorrow when I'm back in the office.

**Comment by andrewbonney** [comment]
I'm using Chrome 72.0.3626.109 (Official Build) (64-bit) on Ubuntu 16.04

**Comment by jasperpeeters** [comment]
`saveSettings` did actually never its job on a "fresh" system where no `test` key existed in the localStorage. During development this was on my system and thus it was executed correctly.
Also the 'Go Back' link should now act like a browser's history.back.

**Comment by andrewbonney** [comment]
That's looking better. I guess my only question is how long this will persist for? If it goes beyond a browser restart is that perhaps a bit long? If the default API versions change (for example) in an update to the test suite, a user would never see this change if so.

**Comment by jasperpeeters** [comment]
Maybe we can use `sessionStorage` instead of `localStorage`. 

> The sessionStorage property allows you to access a session Storage object for the current origin. sessionStorage is similar to localStorage; the only difference is while data stored in localStorage has no expiration time, data stored in sessionStorage gets cleared when the page session ends. A page session lasts for as long as the browser is open and survives over page reloads and restores. Opening a page in a new tab or window will cause a new session to be initiated with the value of the top-level browsing context, which differs from how session cookies work.

I'll give that a try.

**Comment by jasperpeeters** [comment]
That seems to work. Thanks for the hint.

**Comment by andrewbonney** [comment]
Looks good to me. It'll just need the merge conflict with nmos-test.py resolving before we can approve/merge.

**Pull request merged**
