### PR TITLE
packaging both the cert and chain into the pfx

### PR DESCRIPTION
**Pull request by prince-chrismc**

### CODE REVIEW

**Comment by andrewbonney** [comment]
@simonlo-sony did you suggest this wasn't required/recommended? I'm not familiar enough with the Windows requirements.

**Comment by simonlo-sony** [comment]
It does work with chain in pfx, but I think it is ugly to have the chain inside the 'Personal' windows store.  As 'Personal' should only be installed the server pfx certificate, intermediate CA certificate (can be PEM) should be installed inside 'Intermediate Certifiacte Authorities' and Root CA certificate (can be PEM) in the 'Trusted Root Certification Authorities'.

Is it a reason, why you think it's a good idea to have chain in pfx?

**Comment by prince-chrismc** [comment]
To be honest, I have not completely figured out all the details about installing and deploy certificates.

The chain contains the intermediate CA link, which was for my loop-back to pass the verification with only having the pfx installed. I never thought of installing the intermediate separately, nor did I notice there was an 'Intermediate Certifiacte Authorities' section.

Who other then the server would install the server's chain? Other systems would not need it since they would already have the CA root and intermediate to verify with.

Closing the PR since this is not required.

**Comment by garethsb-sony** [comment]
Hi Chris,

> Who other then the server would install the server's chain? Other systems would not need it since they would already have the CA root and intermediate to verify with.

Basically, every device _when acting as a client_ should only need to trust the _root_ CA cert.
Each device when acting as a server should provide a chain including the _server_ cert and the _intermediate_ CA cert which refers to the root CA cert.

Clients need not have the _intermediate_ cert, so servers need to provide a chain.

**Pull request closed without merging**
