### PR TITLE
Add further command line arguments to list and describe tests/suites

### PR DESCRIPTION
**Pull request by andrewbonney**
Following a request from Felix at CBC, I've added some extra command line arguments (and modified one) to allow listing and describing of suites and tests.

### CODE REVIEW

**Comment by andrewbonney** [comment]
> Any reason we shouldn't include 'auto' and 'all' in `--describe-tests`? Seems counter intuitive that they should be allowed in `--selection` and included in `--list-tests` but not in `--describe-tests`?

Not particularly, it was only that they didn't have a pre-defined description. I'll just add one manually.

> One minor thing we could deal with later is that if you forget to specify `--suite` then e.g. `--list-tests` is just ignored and the test runner goes into interactive mode.

I'll see if there's anything I can do quickly to prompt if it's likely arguments have been specified incorrectly.

**Comment by garethsb-sony** [comment]
> Not particularly, it was only that they didn't have a pre-defined description. I'll just add one manually.

LGTM

> I'll see if there's anything I can do quickly to prompt if it's likely arguments have been specified incorrectly.

Tried it and it works, but feels a tiny bit fragile. I've just noticed [ArgumentParser.add_subparsers](https://docs.python.org/3/library/argparse.html#sub-commands). I haven't thought it through, but maybe making `--suite` a 'sub-command' might give us this kind of checking for free? Or would [ArgumentParser.add_mutually_exclusive_group](https://docs.python.org/3/library/argparse.html#mutual-exclusion) help?

**Comment by andrewbonney** [comment]
This may be a little better. I'm not 100% happy with the naming of suite/key, but it seems to do a better job.

**Comment by garethsb-sony** [comment]
Agreed.

Just throwing out suggestions...

Turn 'key' into a positional arg? (And then could call it something like 'suite_name', potentially? Or not sure what happens if you just call it 'suite' even?)

Not sure if you can/would want to cheat and make the name of the command '--suite' so it looks like a normal command line arg?

**Comment by andrewbonney** [comment]
I couldn't get it to be happy calling it '--suite', but 'suite' worked.

**Comment by garethsb-sony** [comment]
OK. Took me a little bit of trial and error to work out how to see help for the 'suite' command options. It's

```
python3 nmos-test.py suite -h
```

Which responds

```
usage: nmos-test.py suite [-h] [--list-tests] [--describe-tests]
                          [--selection SELECTION] [--host [HOST [HOST ...]]]
                          [--port [PORT [PORT ...]]]
                          [--version [VERSION [VERSION ...]]]
                          [--ignore [IGNORE [IGNORE ...]]] [--output OUTPUT]
                          suite

positional arguments:
  suite                 select a test suite to run tests from in non-
                        interactive mode

optional arguments:
...
```

I think that makes sense?

**Comment by andrewbonney** [comment]
Yeah that's it. I can't see an obvious way to make it any clearer without changing variable names and introducing extra arguments.

**Pull request merged**
