### PR TITLE
use nmos-mocks.local as the mock node name in mDNS mode

### PR DESCRIPTION
**Pull request by alanb-sony**

### CODE REVIEW

**Review by garethsb-sony — APPROVED** [review]
LGTM

**Review by prince-chrismc — COMMENTED** [review]
In secure mode, ideally you would like the host name to match the certificate even with mDNS?

**Comment by alanb-sony** [comment]
nmos-mocks.local is in the certificate as an alternative name, in mDNS mode the other host name might not be resolvable

**Review by prince-chrismc — APPROVED** [review]
Sounds Reasonable 👍

**Pull request merged**
