### PR TITLE
Advanced testing of basic/RQL/downgrade/ancestry queries

### LINKED ISSUE #144: IS-04: Add test that Query API /subscriptions endpoint doesn't support 'query.downgrade'
From https://github.com/AMWA-TV/nmos-testing/pull/142#issuecomment-466983216:

Add a ``test_22_1`` that /subscriptions endpoint doesn't support 'query.downgrade'.

### PR DESCRIPTION
**Pull request by andrewbonney**
Work in progress...

Resolves #144

### CODE REVIEW

**Comment by andrewbonney** [comment]
This is almost complete. I'm not adding testing of downgrade/ancestry via WebSocket in this PR as they're a bit more complex, but I'll get to them later.

Just finding an issue with repeatability of test_23_1 when run with 'all' tests which I'll resolve before requesting review.

**Comment by andrewbonney** [comment]
I'm pretty sure the remaining issue is down to slow WebSockets in our implementation so I'm looking into that, but I'd appreciate others testing/reviewing in the meantime. In particular I can't test the RQL WebSocket tests, so whilst it's very similar to the basic query one I'd appreciate confirmation that it's possible to pass.

**Comment by garethsb-sony** [comment]
I've added some 201 args to `post_resource` calls where the tests are updating resources, to ensure it does a "bump version", otherwise the registry should respond with 400 Bad Request due to our updating resource properties without updating resource version.

**Comment by andrewbonney** [comment]
Fair enough. I don't believe our implementation checks that at present, but this certainly won't cause any adverse effects.

**Comment by garethsb-sony** [comment]
I now have a failure of `test_31` because it requests a subscription with `"resource_path": "/nodes"` and `"persist": false`, about 10 or so seconds after ``test_22_1`` first does this. The Registry thus returns the existing subscription object... but by the time `test_31` comes to connect to the WebSocket (another couple of seconds later, thus about 12 seconds or so after the subscription was last in use), the Registry has garbage-collected the subscription.


Any suggestions what to do about that? I believe the Registry behaviour is correct.

We could use persistent subscriptions, but then we'd have to clean them up?

Or ``test_31`` could connect to the WebSocket immediately after the ``POST``? There would still be a small window where it could get garbage collected.

**Comment by andrewbonney** [comment]
Interesting. I believe in our case we clean up unused subscriptions as soon as the last client disconnects which is probably why we're not seeing the same thing.

I'd be happy with either workaround suggested. There are potentially lots of failure cases where we'd need to make sure to clean up persistent subscriptions if using that method, but technically we should already be calling the WebSocket disconnect method upon failure, which we're not doing.

I guess the thing to consider is that two Query API clients could do the same thing in a real situation (ie. one disconnects just before the next one does a POST), so whilst there's nothing technically wrong from a spec point of view, the implementation may cause unexpected failures in rare cases?

**Comment by garethsb-sony** [comment]
Equally, I'm seeing failures in ``test_27`` with "Cannot execute test, as expected resources are not registered" because with all our wonderful new intervening test cases, slightly more than 12 seconds have passed since the nodes resource was posted by ``test_03``.

**Comment by andrewbonney** [comment]
> Equally, I'm seeing failures in `test_27` with "Cannot execute test, as expected resources are not registered" because with all our wonderful new intervening test cases, slightly more than 12 seconds have passed since the nodes resource was posted by `test_03`.

Ok, I think that one needs a fix. As it waits for the full garbage interval beforehand we can probably afford to re-post all the resources at the start of that individual test and then wait for them to expire.

**Comment by garethsb-sony** [comment]
> I guess the thing to consider is that two Query API clients could do the same thing in a real situation (ie. one disconnects just before the next one does a POST), so whilst there's nothing technically wrong from a spec point of view, the implementation may cause unexpected failures in rare cases?

Yep, I was concerned by that when I implemented it. Looking back at the IS-04 documentation it only says "In normal operation, once a websocket has no more clients subscribed to it the Query API may automatically remove it and its corresponding HTTP-advertised subscription object. " I guess that 'may' is a bit vague.

The reason I implemented the removal of the subscription object via the same garbage collection mechanism as the resources, was that it also solved the problem of getting rid of a non-persistent subscription which never received _any_ WebSocket connections.

**Comment by andrewbonney** [comment]
Makes sense. I'm happy to make changes to the tests as there's clearly nothing wrong with the way it's implemented to the letter of the spec. Do you have any preference for the resolution out of the two suggested?

**Comment by garethsb-sony** [comment]
The good news is if I bump `GARBAGE_COLLECTION_TIMEOUT` in `Config.py` to 30 seconds, and do the equivalent thing in our registry, all these new tests pass.

**Comment by garethsb-sony** [comment]
> Makes sense. I'm happy to make changes to the tests as there's clearly nothing wrong with the way it's implemented to the letter of the spec. Do you have any preference for the resolution out of the two suggested?

Well, the race condition between a POST /subscriptions (especially one returning a 200 OK) and a WebSocket connection, is something that has been low down on my list of possible spec issues to bring up. So maybe that's worth filing in nmos-discovery-registration. I think my solution for now in the Registry is to modify the behaviour of a 200 response to a POST /subscriptions to extend the lifetime if the subscription object has no current WebSocket connections. Whether that should be added to the spec, or is a QoI issue, I'm not sure?

Once I've done that, probably no change to test suite necessary for the ``test_22_1`` .. ``test_31`` issue, do you think?

The ``test_03`` .. ``test_27`` issue does still need fixing, like you say.

**Comment by andrewbonney** [comment]
Ok. If you're happy with that it works for me. As you say there's probably a need for something more explicit around the best way to handle garbage collection of subscriptions and their potential lifetime extension in the spec.

I'll take a look at a fix for `test_27`.

**Pull request merged**
