### PR TITLE
Show how to publish the Testing Façade port

### PR DESCRIPTION
**Pull request by garethsb**

### CODE REVIEW

**Review by andrewbonney — DISMISSED** [review]

**Comment by garethsb** [comment]
Hmm, @hrbriggs and I suspect that these instructions were already incomplete, because they don't publish the ports for the mock Node, Registry, etc.

**Comment by garethsb** [comment]
@andrewbonney, @hrbriggs, what do you think? The testing tool uses quite a few ports via hard-coded relative offsets from `CONFIG.PORT_BASE`. All of those ports should presumably be needed in the `docker run` command... That's going to be frustrating to keep the docs here in sync with the code...

(We're not even currently describing that the documented `5000` is actually `CONFIG.PORT_BASE`, and we might want to reconsider whether `CONFIG.TESTING_FACADE_PORT` ought to be hard-coded as `5001`, overlapping with the `CONFIG.PORT_BASE + <N>` range.)

Or should we just suggest using [host networking](https://docs.docker.com/network/host/) even though I don't think that works on Windows or macOS?

**Comment by garethsb** [comment]
Ports currently used by the testing tool... mostly at fixed offsets from `PORT_BASE` (5000).

* 5000 - testing tool webapp and Answer API
* 5001 (`TESTING_FACADE_PORT`) - testing façade webapp and Question API
* 5101-5106 - mock Registration API and Query API
* 5201 - mock Node API
* 5301-5106 - mock System API
* 444 (hard-coded) - timeout testing
* 6000- (`WEBSOCKET_PORT_BASE`) - mock Query API WebSocket (currently at most one per resource type, I think)

Is it worth adding the `EXPOSE` entries for these (with comments warning that they may be overridden by _UserConfig.py_)?

**Comment by hrbriggs** [comment]
No I agree just the publishing of ports isn't enough to make it work. I've tested it and the resources are made available but the mDNS advertisements don't use the correct IP address and can't be discovered. `docker run -d --network="host" amwa/nmos-testing` uses the correct IP address and makes all the ports available.

**Review by andrewbonney — APPROVED** [review]

**Pull request merged**
