### PR TITLE
is0401: ensure a registry is advertised when checking Node mDNS

### LINKED ISSUE #212: IS-04-01 test_12 dependency?
Test 12 in the Node API suite checks that there are no 'ver_' TXT records in registered operation.

But obviously this relies on a Registry being enabled, which as far as we can see isn't ensured by this test itself, so it's only likely to pass currently if run sufficiently soon after one of the tests that does. 

Should it do something similar to `test_21` do you think, @andrewbonney?

We'd like to make `do_registry_basics_prereqs` wait for a bit after the last registry is disabled (like it does after all the others) in order to make `test_21` reliable, but that will make `test_12` always fail right now.

### PR DESCRIPTION
**Pull request by andrewbonney**
Should resolve #212

### CODE REVIEW

**Comment by garethsb-sony** [comment]
Another issue @simonlo-sony has seen with `test_12` is that `MdnsListener.get_service_list` only ever seems to return one entry, even when the test suite and the node-under-test are run on the same machine with multiple interfaces. `avahi-browse` (or `dns-sd`) correctly resolves multiple addresses in this case, but `MdnsListener.get_service_list` only returns one. Sometimes it _is_ the primary address and the test passes, other times it gets back the `127.0.0.1` advertisement and the test fails. I can't actually see how python-zeroconf module can return more than one address... :-/ Raise this as separate issue?

**Comment by andrewbonney** [comment]
Yeah, lets have that as a separate bug. Our own implementation is using python-zeroconf and can handle this (at a glance by using multiple instances), but the usage here is a little simpler.

**Comment by garethsb-sony** [comment]
OK.

The next problem is that now*, running e.g. `test_11` (or any other test that performs the prereqs) and `test_12` before `test_15` can cause that last one to fail. I think that's because a heartbeat gets through to the 5001 registry during `test_12` so that the last heartbeat at that registry is _after_ the earliest heartbeat at the 5002 registry recorded during the prereqs. Not sure what to do about this?

*Actually that's after the one further tweak that I think we need for (now somewhat related) `test_21`: https://github.com/AMWA-TV/nmos-testing/pull/210#issuecomment-486689839

**Comment by garethsb-sony** [comment]
@andrewbonney, do you think the best way to resolve this final issue is actually to advertise a different Registry than the ones used in the prereqs? Or possibly cheat (I'm just now thinking) and reorder `test_15` before `test_12`?

**Comment by andrewbonney** [comment]
Ha, that's annoying. Either that or we need to store the results of the prereqs registry tests (get_post_data() etc) elsewhere so that they can be accessed later?

It's tempting to re-order, but if we come up with further tests which need to access the prereqs data we may find we need to do the same again in the future, which doesn't seem ideal.

**Comment by andrewbonney** [comment]
Very much untested, but that commit may sort it out. I'll try and check it this afternoon.

**Comment by garethsb-sony** [comment]
We're now testing #187 + #211 + #213 and will report back shortly!! Hoping we can get all of these merged...

**Pull request merged**
