### PR TITLE
Update GH Actions deploy workflow to build multi-arch

### LINKED ISSUE #579: No ARM nmos-testing container - Breaks "easy-nmos" solution on ARM
Currently we have a mismatch with "easy-nmos" when it is installed on ARM CPU architectures. The nmos-cpp containers support multi-arch and are built for AMD64 and ARM64/32. The nmos-testing container is only built for AMD64... This means easy-nmos fails to run the nmos-testing container on ARM CPU installs.

Can we move the nmos-testing container from a Docker Hub build process to a GitHub Actions build process? This will give you the ability to build the container for multi-architecture under the Docker "buildx" process. You can then push the container to Docker Hub using a multi-arch manifest which resolves the above issues.

I'm happy to work with someone on this... Ultimately it will give AMWA a better solution as the nmos-testing container will be fully supported on ARM CPU architectures.

### PR DESCRIPTION
**Pull request by andrewbonney**
Following issues with the amd64 Docker image, this attempts to correct the issue and build for multi-arch.

Resolves #579

### CODE REVIEW

**Comment by garethsb** [comment]
Hi Andrew,

Thanks for doing this!

If it helps, we've found the https://github.com/ilteoood/docker_buildx action to work really well, and avoids having to deal with QEMU yourself.

https://github.com/rhastie/build-nmos-cpp/blob/369c7cc344c37afc143b2c969bbbdf826e72d08f/.github/workflows/ci-build-test-publish.yml#L288-L298

Please could we have `linux/amd64`, `linux/arm64` and `linux/armv7`? I believe current Raspian is still on 32-bit ARM.

**Comment by peterbrightwell** [comment]
Looks good. This does mean nmos-testing differs from the `.deploy` approach used for the render scripts... but that's a small price to place for multi-arch support, and I would be interested in trying it for the render build also (I often build manually on an M1 mac and it has to translate).

**Review by peterbrightwell — DISMISSED** [review]
Looks good -- adding `linux/armv7` as Gareth suggests seems sensible.

Note that this does mean nmos-testing differs from the `.deploy` approach used for `nmos-doc-build-scripts` docker... but that's a small price to place for multi-arch support, and I would be interested in trying it there also (I often build manually on an M1 mac and it has to translate, and the other box on my desk is linux/arm64). 

#619 shouldn't affect this of course but will need a rebuild.

**Review by peterbrightwell — APPROVED** [review]

**Comment by garethsb** [comment]
@peterbrightwell can you remember why we left the _.deploy/docker-compose.yml_ file behind?

**Pull request merged**
