### PR TITLE
Add support for downgrade queries

### PR DESCRIPTION
**Pull request by andrewbonney**
Adding this as a placeholder as I intend to work on it next.

### CODE REVIEW

**Comment by andrewbonney** [comment]
I think this now covers most cases. Note that it only tests /nodes. I could expand it to cover this if desired.

**Comment by andrewbonney** [comment]
Thanks for testing

> One thing is that if you ask to test an unsupported version (e.g. v1.2 in above case), you get an unhelpful _Fail_ message like "Query API failed to respond with a Node when asked to downgrade to v1.1". But that applies to almost all the existing tests... I wonder if we should add a precondition check to all tests based on the response to /x-nmos/{api}?

Yeah that sounds sensible. Would you mind adding an issue and we can look at covering the general case?

> And yes, I hate the name 'downgrade query'.

Sorry! Hindsight and all. The thinking at the time (I suspect) was that the query itself is the thing being downgraded, rather than the resources being returned which are effectively 'upgraded'.

> Do you think we add a test that shows subscriptions don't support downgrade? (More important - see my regular confusion above - is the test that v1.x /subscriptions doesn't return v1.x+1 subscriptions of course.)

I think that one warrants a specific test which checks both with/without the downgrade query in place. Again, probably worth highlighting through an issue for now.

**Comment by garethsb-sony** [comment]
@andrewbonney I realise that ``test_22`` doesn't have a 501 check. Didn't it ought to do that and refer to https://github.com/AMWA-TV/nmos/wiki/IS-04#registries-downgrade-queries if so?

**Comment by garethsb-sony** [comment]
Is the correct resource stripping (/downgrade) actually covered anywhere by the test suite or an existing issue or PR?

**Comment by andrewbonney** [comment]
Added a 501 test if you wouldn't mind re-reviewing. On resource stripping, no this isn't tested yet. I've added a note to https://github.com/AMWA-TV/nmos-testing/issues/114

**Pull request merged**
