### PR TITLE
Update certificate generation for BCP-003

### PR DESCRIPTION
**Pull request by andrewbonney**
This addresses some issues highlighted in https://github.com/AMWA-TV/nmos-testing/pull/187 and https://github.com/AMWA-TV/nmos-testing/issues/206

I haven't tried these out yet, but that's the next step.

### CODE REVIEW

**Comment by andrewbonney** [comment]
I haven't tested verification of the '.local' name yet, but I can see that in the SAN. From my own tests I think the other issues noted are resolved by this (EC params and appending the certificate's intermediate for example).

**Comment by garethsb-sony** [comment]
That all makes sense to me - thanks, Andrew. We'll try it out.

**Comment by garethsb-sony** [comment]
Andrew, I think the chain certs need the root CA cert appended as well as the intermediate CA?

**Comment by andrewbonney** [comment]
That's fine, and makes sense. I was a little unsure when I put that together and partially working from memory of deploying TLS elsewhere.

**Pull request merged**
