### PR TITLE
in Registry.py, request.json throws 400 Exception

### PR DESCRIPTION
**Pull request by thosil**
test_05 requires to POST to health/node/<node_id> with no body, but the mock perform a "request.json" which throw an Exception if there's no content (or no valid json).
A request.get_json(False, True) parses the body if any or return None if there's no content.

### CODE REVIEW

**Comment by garethsb-sony** [comment]
Does this depend on your version of flask? This has always worked for me. The flask 1.0 documentation for `request.json` says "This will contain the parsed JSON data if the mimetype indicates JSON (application/json, see is_json()), otherwise it will be None."

**Comment by garethsb-sony** [comment]
A guess - you might see that exception if the Node sent `Content-Type: application/json` without any content? That would be a Node bug that we ought to report, not mask.

**Comment by garethsb-sony** [comment]
> A guess - you might see that exception if the Node sent ``Content-Type: application/json`` without any content? That would be a Node bug that we ought to report, not mask.

I've just tested a Node doing that, and the mock Registry behaves as I suspected, returning 400 to the Node and reporting "Not enough heartbeats were made in the time period." for ``test_05``.

@thosil can you confirm that's what is happening in your system?

I found the test also passes, when I believe it shouldn't, with a heartbeat having ``Content-Type: application/json`` and body of ``null``.

See https://github.com/AMWA-TV/nmos-discovery-registration/issues/36 for background to this. It introduced the following note into [APIs - Client Side Implementation Notes](https://github.com/amwa-tv/nmos-discovery-registration/blob/v1.2.x/docs/2.2.%20APIs%20-%20Client%20Side%20Implementation%20Notes.md#empty-request-bodies):

> A number of API resources specify HTTP requests with no request body (headers only). These commonly include HTTP GET, HEAD, OPTIONS and DELETE operations, but may include other HTTP methods in some circumstances. When performing API requests which have no specified request body schema, clients SHOULD NOT send any body payload and SHOULD NOT set the HTTP `Content-Type` header. Clients MAY set the `Content-Length` header to a value of 0 to indicate this empty body, but this is not mandated.

@andrewbonney if you agree with my understanding, I'll make a PR to fix `Registry` and `test_05` accordingly. Based on the SHOULD NOTs in the quoted paragraph, and the reasoning in https://github.com/AMWA-TV/nmos-discovery-registration/issues/36, my take is that `Content-Type: application/json` with empty body is reasonably an error (FAIL) because an empty string isn't JSON, but `Content-Type: application/json` with `null` or `{"foo":"bar"}` ought only to be a WARNING (though it's currently a FAIL), as did in fact any `Content-Type:` or any non-empty body?

**Comment by thosil** [comment]
I double check ;-)
Flask version is 1.02
You're right, I'm setting the content-type to application/json without content and it's exactly what the test framework receive.
Still got some problems, but I'm not sure yet if the problem is on my side or not.

I realize that my correction was a little too naive, I have no problem that it is denied for a more complete patch.

**Comment by andrewbonney** [comment]
> @andrewbonney if you agree with my understanding, I'll make a PR to fix `Registry` and `test_05` accordingly. Based on the SHOULD NOTs in the quoted paragraph, and the reasoning in [AMWA-TV/nmos-discovery-registration#36](https://github.com/AMWA-TV/nmos-discovery-registration/issues/36), my take is that `Content-Type: application/json` with empty body is reasonably an error (FAIL) because an empty string isn't JSON, but `Content-Type: application/json` with `null` or `{"foo":"bar"}` ought only to be a WARNING (though it's currently a FAIL), as did in fact any `Content-Type:` or any non-empty body?

That sounds reasonable as a fix to me

**Comment by garethsb-sony** [comment]
Thanks. Closing in favour of #171.

**Pull request closed without merging**
