### PR TITLE
Fix GenericTest by taking into account Content-Type. This is mainly t…

### PR DESCRIPTION
**Pull request by gwgeorgea**
Fix GenericTest by taking into account Content-Type. This is mainly to support edid content which is widely used in IS-11

### CODE REVIEW

**Comment by garethsb** [comment]
Can you use `omit_paths` for EDID endpoints rather than do this which I think would allow inappropriate content type for many JSON endpoints?

**Comment by garethsb** [comment]
@gwgeorgea we can discuss this on the activity group channel on Slack if you like :-)

(Also note, GitHub Actions linting is now working again.)

**Comment by gwgeorgea** [comment]
> @gwgeorgea we can discuss this on the activity group channel on Slack if you like :-)
> 
> (Also note, GitHub Actions linting is now working again.)
No problem for slack.
Regarding Lint, can I trigger the job again ? Appart from adding a new commit to the PullRequest.

**Comment by garethsb** [comment]
> Regarding Lint, can I trigger the job again ? Appart from adding a new commit to the PullRequest.

You can't, but I can, and I already did, so you can see the failures already.

**Comment by garethsb** [comment]
Apologies, fat finger closed pull request unintentionally! 👇

**Comment by garethsb** [comment]
You can run `flake8 .` locally to check for lint errors.

**Pull request closed without merging**
