### PR TITLE
is0401: ensure mock registry interactions use correct version

### PR DESCRIPTION
**Pull request by andrewbonney**

### CODE REVIEW

**Comment by andrewbonney** [comment]
Hmm, that was meant to be covered by `parent_resource_type`. It should be looking for source_id instead for v1.0.

**Comment by andrewbonney** [comment]
Oh I understand, in this case of course it thinks we're testing v1.2. Yes, I think an exception handler would be appropriate.

**Comment by andrewbonney** [comment]
Added that, although I may not get chance to test it today.

**Comment by garethsb-sony** [comment]
> Added that, although I may not get chance to test it today.

Ha, I'd just tested my version of the same fix before pushing... I'll test yours!

**Comment by andrewbonney** [comment]
Oops, feel free to use either!

**Comment by garethsb-sony** [comment]
No worries, only difference was I'd put the `try`...`except` inside the `for` loop and used "*a* registered Foo" instead of "*the* registered Foo" in the message!

**Pull request merged**
