### PR TITLE
IS0402 - Test 29_1: Fixed uncaught exception if key is missing

### PR DESCRIPTION
**Pull request by jasperpeeters**
Little one - checking if `secure` key is available before access

### CODE REVIEW

**Comment by garethsb-sony** [comment]
Hmm, probably `ws_href` ought to have a consistent check, and actually I'm not sure why we're not just catching `KeyError` consistently in this test suite for missing JSON keys?

**Comment by jasperpeeters** [comment]
> [...] and actually I'm not sure why we're not just catching `KeyError` consistently in this test suite for missing JSON keys?

Agreed.
If there is no reason not to, I could add an additional catch block in the `GenericTest.py` (next to the the one of the `NMOSTestExceptions`).

**Comment by garethsb-sony** [comment]
Hmm, that's a possibility, although it seems a bit wide in scope (`KeyError` could come from non-JSON objects). If every response were validated against the JSON Schema, that'd solve the problem too?

**Comment by garethsb-sony** [comment]
Potentially we should add schema validation using `check_response` after all instances of `do_request`, but let's focus on those that haven't already been tested in the "auto" tests (most GET requests will have been, DELETE gets a 204 empty response, but POST and PUT responses need checking). That means:

**IS-04-02**

* POST /subscriptions (`post_subscription`) - which would solve this particular case
* POST /resource (`post_resource`)
* POST /health/nodes/{nodeId} (`test_30`)

**IS-04-01**

* PUT /receivers/{receiverId}/target (`do_put_receiver`)

**IS-05-01**

* PATCH /single/{resourceType}/{resourceId}/staged (`checkCleanRequestJSON`)

**Comment by jasperpeeters** [comment]
> Potentially we should add schema validation using `check_response` after all instances of `do_request`, but let's focus on those that haven't already been tested in the "auto" tests (most GET requests will have been, DELETE gets a 204 empty response, but POST and PUT responses need checking). That means:
> 
> **IS-04-02**
> 
>     * POST /subscriptions (`post_subscription`) - which would solve this particular case
> 
>     * POST /resource (`post_resource`)
> 
>     * POST /health/nodes/{nodeId} (`test_30`)
> 
> 
> **IS-04-01**
> 
>     * PUT /receivers/{receiverId}/target (`do_put_receiver`)
> 
> 
> **IS-05-01**
> 
>     * PATCH /single/{resourceType}/{resourceId}/staged (`checkCleanRequestJSON`)

Makes sense - is on my todo

**Comment by jasperpeeters** [comment]
> Hi @jasperpeeters. Please would you see if the addition today of schema validation of `post_subscription` solves this issue (the uncaught test suite exception) for you without the need for the explicit check? Thanks!

Yep - getting a clean "Response schema validation error" with the old configuration instead of the uncaught exception.
Thanks!

**Pull request closed without merging**
