### PR TITLE
Update 2.2. Usage - Testing BCP-003-01 TLS.md

### PR DESCRIPTION
**Pull request by peterbrightwell**
This links to the dir rather than the readme directly

### CODE REVIEW

**Comment by garethsb** [comment]
Please can we rebase this on latest, and check the publication? 🙏

**Comment by peterbrightwell** [comment]
Did a rebase and tried rendering my branch and sadly it doesn't fix the the links. We could rewrite them explicitly or make further changes to fix-links.sh in the render scripts... @garethsb what do you think?

**Comment by garethsb** [comment]
Stepping back... do we think that _testssl/README.md_ and _test_data/BCP00301/README.md_ should be part of the published "user facing" documentation on specs.amwa.tv, or are they "implementation detail" that should be kept as (only) GitHub docs?

**Comment by peterbrightwell** [comment]
I think it would be fine to stop rendering those (and it would remove complexity from nmos-render-scripts). The text in https://specs.amwa.tv/nmos-testing could then link to the relevant dirs of the repository?  Or just "see the `testssl/` dir in <https://github.com/AMWA-TV/nmos-testing> etc?

**Comment by peterbrightwell** [comment]
Tried this again with `publish-fix-ssl-links` branch, which is identical to this one but matches the render regex and it looks like it's ok after all.   So the rendered links will now go to the relevant repo dir.

**Review by garethsb — APPROVED** [review]

**Pull request merged**
