### PR TITLE
Add test  subscription request

### PR DESCRIPTION
**Pull request by jasperpeeters**

### CODE REVIEW

**Comment by andrewbonney** [comment]
I wonder if the request JSON needs passing through a form of the downgrade_resource function in order to strip the 'secure' key when testing API v1.0

**Comment by jasperpeeters** [comment]
> It would probably be worth checking explicitly for a 201 response code in this case too as opposed to a 200, given that this will be the first time in the test suite we've called the subscriptions endpoint.

This requires that the registry is tested in a "clean" environment, right? I intentionally allowed a 200 in case the same topic was already requested already by another non-test related device / application.

**Comment by andrewbonney** [comment]
Ah yes, good point.

**Comment by garethsb-sony** [comment]
@andrewbonney, @jasperpeeters, if the test requested a persistent subscription - and deleted it after - we'd always get a 201, right? Although actually, both cases may be good to test...

**Comment by andrewbonney** [comment]
Yes that sounds correct. Probably an extra test as you suggest.

**Pull request merged**
